### ISSUE TITLE
連休やること

### ISSUE THREAD

**Issue by imoyoukan** [imoyoukan/imoyoukan#1]
やる
---
### 読む
どれか
* マスタリングTCP/IP
* 入門Git
* 象本

### 行く
どうしよう

### 環境構築
* MBPをAnsibleで色々する
* dotfileの整理
* VPSをDockerホストにしようかなー

### 作る
適当になんか

**Comment by Blacks-G** [comment]
# 行き先のアイディア

- 日光
    - 温泉街
    - 東照宮を写真に取れる
    - 日帰りできる近さ
- 熱海
    - 温泉街
    - 富士山を眺めつつ海を写真におさめられる
    - 日帰りできる近さ
- 河口湖
    - 観光地
    - 富士山を眺めつつ、雄大な湖を写真におさめられる
    - JRと富士急行線で日帰りできる近さ
- 土浦
    - 観光地
    - ガルパン
    - 戦車見ようぜ戦車

**Comment by imoyoukan** [comment]
日帰りできる近さ :+1:

**Comment by imoyoukan** [comment]
3/13
---

### 予定
- [ ] 部屋の掃除
- [ ] 連休中の計画たてる
- [ ] リーダブルコード読む

**Comment by imoyoukan** [comment]
日帰り鎌倉旅行計画
---
気になる
* 鎌倉高校前駅 http://www.enoden.co.jp/map/kamakurahighschool.html
* イワタコーヒー http://tabelog.com/kanagawa/A1404/A140402/14002091/
* 稲村ヶ崎温泉 http://inamuragasaki-onsen.com/index.html

**Comment by imoyoukan** [comment]
3/14(土) 2日目
---
### 予定
- [ ] VPSの環境構築
- [ ] dotfile整理

**Comment by imoyoukan** [comment]
3/15(日) 3日目
---
### 予定
今日こそ
- [ ] VPSの環境構築
- [ ] dotfile整理
- [ ] なんか描く

**Comment by imoyoukan** [comment]
3/16(月) 4日目
---
### 予定
そろそろ
- [ ] Aチャンネル展にいく
- [ ] Macの環境構築
- [ ] dotfile整理

**Comment by imoyoukan** [comment]
3/17(火) 5日目
---
### 予定
折り返しなのでそろそろ外に出たい(天気が良ければ)
- [ ] 鎌倉に行きたい

**Comment by imoyoukan** [comment]
鎌倉issue :point_right: https://github.com/imoyoukan/imoyoukan/issues/2

**Comment by imoyoukan** [comment]
3/18(水) 6日目
---
### 予定
- [ ] Macの環境構築終わらせたい

**Comment by sgymtic** [comment]
昨日(3/180の結果と今日(3/19)の予定はどうなんでしょう？？

**Comment by imoyoukan** [comment]
3/19(木) 7日目
---
- [ ] なんか食べる
