### ISSUE TITLE
鎌倉

### ISSUE THREAD

**Issue by imoyoukan** [imoyoukan/imoyoukan#2]
行きたい

**Comment by imoyoukan** [comment]
天気 http://weather.yahoo.co.jp/weather/jp/14/4610/14204.html

**Comment by imoyoukan** [comment]
地図 https://www.google.com/maps/d/edit?mid=zjyyairDCFE4.kxSIn5X8yNj0

**Comment by imoyoukan** [comment]
ハナヤマタ http://tsurebashi.blog123.fc2.com/blog-entry-373.html

**Comment by imoyoukan** [comment]
ハナヤマタ https://www.google.com/maps/d/viewer?ll=35.317086,139.534607&brcurrent=3,0x601854c7fb67d4ab:0x11f79cd042272356,1&t=m&source=embed&ie=UTF8&msa=0&spn=0.049024,0.072956&z=13&hl=ja&mid=z_PK56cAHdAw.kKytlcOmN1zA

**Comment by imoyoukan** [comment]
TARITARI http://tsurebashi.blog123.fc2.com/blog-entry-197.html

**Comment by imoyoukan** [comment]
カレー http://tabelog.com/kanagawa/A1404/A140402/14000589/

**Comment by imoyoukan** [comment]
オムライス http://tabelog.com/kanagawa/A1404/A140402/14002141/

**Comment by imoyoukan** [comment]
起きれて元気で晴れてたら今日いく

**Comment by Blacks-G** [comment]
lgtm

**Comment by imoyoukan** [comment]
楽しかった
---
### [▶アルバム](https://t.co/87BDYJDiQi)
![2015-03-17 17 23 00](https://cloud.githubusercontent.com/assets/4360727/6693947/0a089468-cd1a-11e4-8601-e982ea650825.jpg)

**Comment by sgymtic** [comment]
LGTM
